### ISSUE TITLE
Backport from Prague

### ISSUE THREAD

**Issue by gurukamath** [ethereum/execution-specs#1051]
```[tasklist]
### Tasks
- [x] Adding access list addresses moved up in the logic compared to prague. See [this](https://github.com/ethereum/execution-specs/blob/1ea4a8d30d68bb819e77ff52eeb2095ae3c67f5f/src/ethereum/prague/utils/message.py#L82)
- [x] Change variable name from BLOB_GASPRICE_UPDATE_FRACTION to BLOB_BASE_FEE_UPDATE_FRACTION in cancun. See [PR](https://github.com/petertdavies/execution-specs/pull/3#issue-2729552764)
- [x] Move refund counter to the top of `process_message_call`. See [this](https://github.com/ethereum/execution-specs/blob/1ea4a8d30d68bb819e77ff52eeb2095ae3c67f5f/src/ethereum/prague/vm/interpreter.py#L111)
- [x] Create the `encode_receipt` function. See [this](https://github.com/ethereum/execution-specs/blob/1ea4a8d30d68bb819e77ff52eeb2095ae3c67f5f/src/ethereum/prague/fork.py#L501)
- [x] Create `process_system_transaction` function. See [this](https://github.com/ethereum/execution-specs/commit/247fd14d0edf10953c6655029a576f8fc0030f2e#diff-1ead0e19bcf5b72f6e0ff1f07a9d44a25a738020803d5ea42839da1e3d58a8c5R519)
- [x] Catch invalid signatures. See [this](https://github.com/ethereum/execution-specs/commit/d55ada18a1f9e6e8f77d2c5d83b0ade30a47e55f)
- [x] re-factor `validate_transaction`. See [this](https://github.com/ethereum/execution-specs/commit/0c56b700a9ce5a1d336c81468eda9d2ad7e55626)
- [x] minor re-factor of `extcodesize`, `extcodecopy` and `extcodehash`. See [this](https://github.com/ethereum/execution-specs/commit/d35af35ae6aba4d369cb15700d3320938441a554#diff-0aedd235b94efdabacd82b86edd6393e9bddd26b67c5377e87d77f33476fca3bR347)
- [x] Explicitly define `code_address` in `call` and `staticcall` opcodes. See [this](https://github.com/ethereum/execution-specs/commit/d35af35ae6aba4d369cb15700d3320938441a554#diff-0aedd235b94efdabacd82b86edd6393e9bddd26b67c5377e87d77f33476fca3bR347)
```

**Comment by SamWilsn** [comment]
Is #1026 covered in this issue?

**Comment by gurukamath** [comment]
> Is #1026 covered in this issue?

Ah yes. Its is covered. However, it looks like I ended up creating duplicate issues for backporting pectra changes. I'll close #1026

**Comment by gurukamath** [comment]
Completed in #1113
