### ISSUE TITLE
4844: Add tests for invalid blob-related header fields

### ISSUE THREAD

**Issue by marioevz** [ethereum/execution-specs#1466]
```[tasklist]
### Tasks
- [ ] Add tests where either the excessDataGas or dataGasUsed fields exceed 64-bit length
- [ ] Add tests where the type-3 tx rlp contains over-length fields
- [x] Add tests where type-3 tx has a nil to address
```
