### ISSUE TITLE
✨(et): make `eest make test` great

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-specs#1503]
The `uv run eest make test` command is an interactive CLI that helps a user create a new test module and function as a starting point to creating a new test. See https://ethereum.github.io/execution-spec-tests/main/writing_tests/.

### Tasks
- [x] ethereum/execution-spec-tests#945
- [x] ethereum/execution-spec-tests#926
- [x] ethereum/execution-spec-tests#946
- [x] https://github.com/ethereum/execution-spec-tests/issues/1179
- [ ] ethereum/execution-specs#1509
- [x] https://github.com/ethereum/execution-spec-tests/issues/1173
- [ ] TBD: Add a `-q` option that causes the verbose explanations/TODOs in the generated module to be omitted
- [ ] If creating a new tests subfolder, also create the `__init__.py` and `spec.py` modules
