### ISSUE TITLE
Write tests for bugs caught while syncing the chain

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#374]
_Originally posted by @lightclient in https://github.com/ethereum/execution-specs/pull/373#pullrequestreview-779880591_

**Should re-check to see if these have been added to EEST since this issue was written**

This is a bit of a meta-issue for tracking bugs that weren't caught by the tests that were triggered while syncing the chain.

These tests should theoretically get upstreamed to https://github.com/ethereum/tests and checked off here once they're merged.

 - [ ] `sstore` persists between transactions (#368)
 - [ ] charge gas for `ECRECOVER`
 - [ ] `blockhash` should hash only the header, not the block (#373)
 - [ ] `signextend` (#375)
 - [ ] Push-data extends past end of contract code (#375)
 - [ ] Deploying an empty contract (#375)
 - [ ] `ECRECOVER` with truncated call data (#445)
 - [ ] Logs emitted during `CREATE2` [#466](https://github.com/ethereum/execution-specs/pull/466#discussion_r845540487)
 - [ ] Blockhash at 255/256/257

**Comment by ultratwo** [comment]
I have two more:

- [ ] Doing a `CALL` with non-zero bits in the 8 high bytes
- [ ] Check compliance with condition d) in EIP 161

**Comment by gurukamath** [comment]
- [ ] Check compliance with [EIP-3607](https://eips.ethereum.org/EIPS/eip-3607) #583

**Comment by SamWilsn** [comment]
https://github.com/ethereum/execution-spec-tests/issues/866 would probably be useful for this

**Comment by gurukamath** [comment]
Also needd to upstream the `insufficient_balance_for_value` test case that we wrote some time ago, if not done already. See [this](https://github.com/ethereum/execution-specs/blob/78fb726158c69d8fa164e28f195fabf6ab59b915/tests/paris/test_state_transition.py#L96)
